import { SUPABASE_PUBLISHABLE_KEY, SUPABASE_URL } from './supabase-client.js?v=5';
import { callMemberRpc, memberRest, requestPasswordReset, requireMemberSession, signInMember, signOutMember, updateMemberPassword } from './member-auth.js?v=19';

const appCs={home:'Domů',logout:'Odhlásit',privateAccess:'SOUKROMÝ PŘÍSTUP',yourSelection:'Váš výběr.',justForYou:'Jen pro vás.',privacyLine:'Žádný veřejný katalog. Kontakt až po vzájemném zájmu.',loginLabel:'PŘIHLÁŠENÍ',welcomeBack:'Vítejte zpět.',password:'Heslo',signIn:'Přihlásit se',forgot:'Zapomněli jste heslo?',noProfile:'Ještě nemáte profil?',createProfile:'Vytvořit soukromý profil',selectedForYou:'VYBRÁNO PRO VÁS',threeRecommendations:'Vaše tři doporučení.',ofThree:'z 3 dnes',forYou:'Pro vás',choices:'Volby',messages:'Zprávy',profile:'Profil'};
const appCopy={
  cs:appCs,
  de:{...appCs,home:'Start',logout:'Abmelden',privateAccess:'PRIVATER ZUGANG',yourSelection:'Ihre Auswahl.',justForYou:'Nur für Sie.',privacyLine:'Kein öffentlicher Katalog. Kontakt erst bei gegenseitigem Interesse.',loginLabel:'ANMELDUNG',welcomeBack:'Willkommen zurück.',password:'Passwort',signIn:'Anmelden',forgot:'Passwort vergessen?',noProfile:'Noch kein Profil?',createProfile:'Privates Profil erstellen',selectedForYou:'FÜR SIE AUSGEWÄHLT',threeRecommendations:'Ihre drei Empfehlungen.',ofThree:'von 3 heute',forYou:'Für Sie',choices:'Auswahl',messages:'Nachrichten',profile:'Profil'},
  it:{...appCs,home:'Home',logout:'Esci',privateAccess:'ACCESSO PRIVATO',yourSelection:'La tua selezione.',justForYou:'Solo per te.',privacyLine:'Nessun catalogo pubblico. Contatto solo con interesse reciproco.',loginLabel:'ACCESSO',welcomeBack:'Bentornato.',password:'Password',signIn:'Accedi',forgot:'Password dimenticata?',noProfile:'Non hai ancora un profilo?',createProfile:'Crea profilo privato',selectedForYou:'SCELTI PER TE',threeRecommendations:'Le tue tre proposte.',ofThree:'su 3 oggi',forYou:'Per te',choices:'Scelte',messages:'Messaggi',profile:'Profilo'},
  pl:{...appCs,home:'Start',logout:'Wyloguj',privateAccess:'PRYWATNY DOSTĘP',yourSelection:'Twój wybór.',justForYou:'Tylko dla Ciebie.',privacyLine:'Bez publicznego katalogu. Kontakt tylko po wzajemnym zainteresowaniu.',loginLabel:'LOGOWANIE',welcomeBack:'Witamy ponownie.',password:'Hasło',signIn:'Zaloguj się',forgot:'Nie pamiętasz hasła?',noProfile:'Nie masz profilu?',createProfile:'Utwórz prywatny profil',selectedForYou:'WYBRANO DLA CIEBIE',threeRecommendations:'Twoje trzy propozycje.',ofThree:'z 3 dzisiaj',forYou:'Dla Ciebie',choices:'Wybory',messages:'Wiadomości',profile:'Profil'},
  sk:{...appCs,home:'Domov',logout:'Odhlásiť',privateAccess:'SÚKROMNÝ PRÍSTUP',yourSelection:'Váš výber.',justForYou:'Len pre vás.',privacyLine:'Žiadny verejný katalóg. Kontakt až po vzájomnom záujme.',loginLabel:'PRIHLÁSENIE',welcomeBack:'Vitajte späť.',password:'Heslo',signIn:'Prihlásiť',forgot:'Zabudli ste heslo?',noProfile:'Ešte nemáte profil?',createProfile:'Vytvoriť súkromný profil',selectedForYou:'VYBRANÉ PRE VÁS',threeRecommendations:'Vaše tri odporúčania.',ofThree:'z 3 dnes',forYou:'Pre vás',choices:'Voľby',messages:'Správy',profile:'Profil'},
  uk:{...appCs,home:'Головна',logout:'Вийти',privateAccess:'ПРИВАТНИЙ ДОСТУП',yourSelection:'Ваша добірка.',justForYou:'Лише для вас.',privacyLine:'Без публічного каталогу. Контакт лише після взаємного інтересу.',loginLabel:'ВХІД',welcomeBack:'З поверненням.',password:'Пароль',signIn:'Увійти',forgot:'Забули пароль?',noProfile:'Ще немає анкети?',createProfile:'Створити приватну анкету',selectedForYou:'ВИБРАНО ДЛЯ ВАС',threeRecommendations:'Ваші три рекомендації.',ofThree:'з 3 сьогодні',forYou:'Для вас',choices:'Вибір',messages:'Повідомлення',profile:'Профіль'},
  ru:{...appCs,home:'Главная',logout:'Выйти',privateAccess:'ПРИВАТНЫЙ ДОСТУП',yourSelection:'Ваша подборка.',justForYou:'Только для вас.',privacyLine:'Без публичного каталога. Контакт только после взаимного интереса.',loginLabel:'ВХОД',welcomeBack:'С возвращением.',password:'Пароль',signIn:'Войти',forgot:'Забыли пароль?',noProfile:'Ещё нет анкеты?',createProfile:'Создать приватную анкету',selectedForYou:'ВЫБРАНО ДЛЯ ВАС',threeRecommendations:'Ваши три рекомендации.',ofThree:'из 3 сегодня',forYou:'Для вас',choices:'Выбор',messages:'Сообщения',profile:'Профиль'},
  en:{...appCs,home:'Home',logout:'Sign out',privateAccess:'PRIVATE ACCESS',yourSelection:'Your selection.',justForYou:'Only for you.',privacyLine:'No public catalogue. Contact only after mutual interest.',loginLabel:'SIGN IN',welcomeBack:'Welcome back.',password:'Password',signIn:'Sign in',forgot:'Forgot your password?',noProfile:'No profile yet?',createProfile:'Create private profile',selectedForYou:'SELECTED FOR YOU',threeRecommendations:'Your three recommendations.',ofThree:'of 3 today',forYou:'For you',choices:'Choices',messages:'Messages',profile:'Profile'}
};
const authCopy={
  cs:{invalidLogin:'Nesprávný e-mail nebo heslo.',confirmEmail:'Nejdříve potvrďte e-mail.',loginFailed:'Přihlášení se nepodařilo. Zkuste to znovu.',signingIn:'Přihlašujeme…',enterEmail:'Nejdříve zadejte e-mail.',sendingReset:'Odesíláme odkaz pro nové heslo…',resetSent:'Odkaz pro nové heslo jsme poslali na váš e-mail.',resetFailed:'Odkaz se nepodařilo odeslat. Zkuste to znovu.',newPasswordLabel:'NOVÉ HESLO',newPasswordTitle:'Nastavte nové heslo.',newPassword:'Nové heslo',repeatPassword:'Zopakujte heslo',savePassword:'Uložit heslo',passwordShort:'Heslo musí mít alespoň 8 znaků.',passwordMismatch:'Hesla se neshodují.',passwordSaved:'Heslo je uloženo.',linkExpired:'Odkaz už není platný. Pošlete si nový.'},
  de:{invalidLogin:'Falsche E-Mail-Adresse oder falsches Passwort.',confirmEmail:'Bestätigen Sie zuerst Ihre E-Mail-Adresse.',loginFailed:'Die Anmeldung ist fehlgeschlagen. Versuchen Sie es erneut.',signingIn:'Anmeldung läuft…',enterEmail:'Geben Sie zuerst Ihre E-Mail-Adresse ein.',sendingReset:'Wir senden den Link für ein neues Passwort…',resetSent:'Der Link für ein neues Passwort wurde per E-Mail gesendet.',resetFailed:'Der Link konnte nicht gesendet werden. Versuchen Sie es erneut.',newPasswordLabel:'NEUES PASSWORT',newPasswordTitle:'Neues Passwort festlegen.',newPassword:'Neues Passwort',repeatPassword:'Passwort wiederholen',savePassword:'Passwort speichern',passwordShort:'Das Passwort muss mindestens 8 Zeichen lang sein.',passwordMismatch:'Die Passwörter stimmen nicht überein.',passwordSaved:'Das Passwort wurde gespeichert.',linkExpired:'Der Link ist nicht mehr gültig. Fordern Sie einen neuen an.'},
  it:{invalidLogin:'E-mail o password non corretti.',confirmEmail:'Conferma prima il tuo indirizzo e-mail.',loginFailed:'Accesso non riuscito. Riprova.',signingIn:'Accesso in corso…',enterEmail:'Inserisci prima il tuo indirizzo e-mail.',sendingReset:'Stiamo inviando il link per la nuova password…',resetSent:'Il link per la nuova password è stato inviato via e-mail.',resetFailed:'Impossibile inviare il link. Riprova.',newPasswordLabel:'NUOVA PASSWORD',newPasswordTitle:'Imposta una nuova password.',newPassword:'Nuova password',repeatPassword:'Ripeti la password',savePassword:'Salva password',passwordShort:'La password deve contenere almeno 8 caratteri.',passwordMismatch:'Le password non coincidono.',passwordSaved:'La password è stata salvata.',linkExpired:'Il link non è più valido. Richiedine uno nuovo.'},
  pl:{invalidLogin:'Nieprawidłowy e-mail lub hasło.',confirmEmail:'Najpierw potwierdź adres e-mail.',loginFailed:'Logowanie nie powiodło się. Spróbuj ponownie.',signingIn:'Logowanie…',enterEmail:'Najpierw wpisz adres e-mail.',sendingReset:'Wysyłamy link do nowego hasła…',resetSent:'Link do nowego hasła został wysłany e-mailem.',resetFailed:'Nie udało się wysłać linku. Spróbuj ponownie.',newPasswordLabel:'NOWE HASŁO',newPasswordTitle:'Ustaw nowe hasło.',newPassword:'Nowe hasło',repeatPassword:'Powtórz hasło',savePassword:'Zapisz hasło',passwordShort:'Hasło musi mieć co najmniej 8 znaków.',passwordMismatch:'Hasła nie są takie same.',passwordSaved:'Hasło zostało zapisane.',linkExpired:'Link nie jest już ważny. Poproś o nowy.'},
  sk:{invalidLogin:'Nesprávny e-mail alebo heslo.',confirmEmail:'Najprv potvrďte e-mail.',loginFailed:'Prihlásenie sa nepodarilo. Skúste to znova.',signingIn:'Prihlasujeme…',enterEmail:'Najprv zadajte e-mail.',sendingReset:'Odosielame odkaz na nové heslo…',resetSent:'Odkaz na nové heslo sme poslali e-mailom.',resetFailed:'Odkaz sa nepodarilo odoslať. Skúste to znova.',newPasswordLabel:'NOVÉ HESLO',newPasswordTitle:'Nastavte nové heslo.',newPassword:'Nové heslo',repeatPassword:'Zopakujte heslo',savePassword:'Uložiť heslo',passwordShort:'Heslo musí mať aspoň 8 znakov.',passwordMismatch:'Heslá sa nezhodujú.',passwordSaved:'Heslo je uložené.',linkExpired:'Odkaz už nie je platný. Pošlite si nový.'},
  uk:{invalidLogin:'Неправильний e-mail або пароль.',confirmEmail:'Спочатку підтвердьте e-mail.',loginFailed:'Не вдалося увійти. Спробуйте ще раз.',signingIn:'Входимо…',enterEmail:'Спочатку введіть e-mail.',sendingReset:'Надсилаємо посилання для нового пароля…',resetSent:'Посилання для нового пароля надіслано на ваш e-mail.',resetFailed:'Не вдалося надіслати посилання. Спробуйте ще раз.',newPasswordLabel:'НОВИЙ ПАРОЛЬ',newPasswordTitle:'Встановіть новий пароль.',newPassword:'Новий пароль',repeatPassword:'Повторіть пароль',savePassword:'Зберегти пароль',passwordShort:'Пароль має містити щонайменше 8 символів.',passwordMismatch:'Паролі не збігаються.',passwordSaved:'Пароль збережено.',linkExpired:'Посилання вже недійсне. Запросіть нове.'},
  ru:{invalidLogin:'Неверный e-mail или пароль.',confirmEmail:'Сначала подтвердите e-mail.',loginFailed:'Не удалось войти. Попробуйте ещё раз.',signingIn:'Входим…',enterEmail:'Сначала введите e-mail.',sendingReset:'Отправляем ссылку для нового пароля…',resetSent:'Ссылка для нового пароля отправлена на ваш e-mail.',resetFailed:'Не удалось отправить ссылку. Попробуйте ещё раз.',newPasswordLabel:'НОВЫЙ ПАРОЛЬ',newPasswordTitle:'Установите новый пароль.',newPassword:'Новый пароль',repeatPassword:'Повторите пароль',savePassword:'Сохранить пароль',passwordShort:'Пароль должен содержать не менее 8 символов.',passwordMismatch:'Пароли не совпадают.',passwordSaved:'Пароль сохранён.',linkExpired:'Ссылка уже недействительна. Запросите новую.'},
  en:{invalidLogin:'Incorrect e-mail or password.',confirmEmail:'Confirm your e-mail first.',loginFailed:'Sign-in failed. Please try again.',signingIn:'Signing in…',enterEmail:'Enter your e-mail first.',sendingReset:'Sending a new-password link…',resetSent:'A new-password link has been sent to your e-mail.',resetFailed:'The link could not be sent. Please try again.',newPasswordLabel:'NEW PASSWORD',newPasswordTitle:'Set a new password.',newPassword:'New password',repeatPassword:'Repeat password',savePassword:'Save password',passwordShort:'The password must contain at least 8 characters.',passwordMismatch:'The passwords do not match.',passwordSaved:'The password has been saved.',linkExpired:'This link is no longer valid. Request a new one.'}
};
const appLanguage=document.querySelector('[data-app-language]');
let appActive='cs';
function t(key){return authCopy[appActive]?.[key]||authCopy.cs[key]||''}
function setAppLanguage(code){appActive=appCopy[code]?code:'cs';document.documentElement.lang=appActive==='uk'?'uk':appActive;document.querySelectorAll('[data-app-i18n]').forEach(node=>{const value=appCopy[appActive][node.dataset.appI18n];if(value)node.textContent=value});appLanguage.value=appActive;try{localStorage.setItem('duonera-lang',appActive)}catch{}dispatchEvent(new CustomEvent('duonera-language-change',{detail:{language:appActive}}))}
let storedLanguage='cs';try{storedLanguage=localStorage.getItem('duonera-lang')||'cs'}catch{}setAppLanguage(storedLanguage);appLanguage.addEventListener('change',()=>setAppLanguage(appLanguage.value));

const authView=document.querySelector('[data-auth-view]');
const appView=document.querySelector('[data-app-view]');
const loginForm=document.querySelector('[data-login-form]');
const authMessage=document.querySelector('[data-auth-message]');
const logoutButton=document.querySelector('[data-logout]');
const notice=document.querySelector('[data-notice]');
const candidatesRoot=document.querySelector('[data-candidates]');
const profileRoot=document.querySelector('[data-profile]');
let auth=null;
let ownProfile=null;
let choices=new Map();
let recoveryMode=false;

function message(text='',error=false){authMessage.textContent=text;authMessage.classList.toggle('error',error)}
function errorText(error){const value=String(error?.message||'').toLowerCase();if(value.includes('invalid login credentials'))return t('invalidLogin');if(value.includes('email not confirmed'))return t('confirmEmail');return t('loginFailed')}
function publicPhotoUrl(path){if(!path)return'';return`${SUPABASE_URL}/storage/v1/object/public/duonera-discovery-photos/${String(path).split('/').map(encodeURIComponent).join('/')}`}
function tags(profile){return[...(Array.isArray(profile.traits)?profile.traits:[]),...(Array.isArray(profile.interests)?profile.interests:[])].filter(Boolean).slice(0,4)}
function profileAge(profile){return Number(profile.age)||'—'}

function candidateCard(profile,index){const article=document.createElement('article');article.className='candidate';article.dataset.profileId=profile.id;const image=Array.isArray(profile.public_photo_paths)?profile.public_photo_paths[0]:'';const tagMarkup=tags(profile).map(tag=>`<span>${escapeHtml(tag)}</span>`).join('');article.innerHTML=`<div class="candidate-photo"><span class="candidate-index">${index+1} / 3</span><span class="verified" title="Ověřený profil">✓</span></div><div class="candidate-body"><h2>${escapeHtml(profile.first_name||'DUONERA')}, ${profileAge(profile)}</h2><p class="location">${escapeHtml([profile.city,profile.country].filter(Boolean).join(', '))}</p><p class="about">${escapeHtml(profile.about_me||profile.relationship_goal||'Vážný vztah a skutečné setkání.')}</p><div class="tags">${tagMarkup}</div><div class="candidate-actions"><button class="pass" type="button" aria-label="Přeskočit">×</button><button class="interest" type="button">Mám zájem</button></div></div>`;if(image)article.querySelector('.candidate-photo').style.backgroundImage=`url("${publicPhotoUrl(image)}")`;const interest=article.querySelector('.interest');const selected=choices.get(profile.id);if(selected){interest.classList.add(selected.is_mutual?'mutual':'selected');interest.textContent=selected.is_mutual?'Je to vzájemné':'Zájem odeslán'}interest.addEventListener('click',()=>toggleInterest(profile.id,interest));article.querySelector('.pass').addEventListener('click',()=>{article.hidden=true;updateVisibleCount()});return article}
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function updateVisibleCount(){const count=[...candidatesRoot.querySelectorAll('.candidate')].filter(card=>!card.hidden).length;document.querySelector('[data-count]').textContent=String(count)}
async function toggleInterest(profileId,button){button.disabled=true;try{if(choices.has(profileId)){await callMemberRpc('duonera_remove_choice',{target_profile_id:profileId});choices.delete(profileId);button.className='interest';button.textContent='Mám zájem'}else{const result=await callMemberRpc('duonera_choose_profile',{target_profile_id:profileId});const choice={is_mutual:Boolean(result?.mutual)};choices.set(profileId,choice);button.className=`interest ${choice.is_mutual?'mutual':'selected'}`;button.textContent=choice.is_mutual?'Je to vzájemné':'Zájem odeslán';if(choice.is_mutual){document.querySelector('[data-match-copy]').textContent='Je to vzájemné. Nyní můžete bezpečně navázat kontakt.';notice.textContent='Máte vzájemnou volbu. Soukromý kontakt je připraven.'}}}catch(error){notice.textContent=error.message||'Volbu se nepodařilo uložit.'}finally{button.disabled=false}}

async function fetchDiscovery(){const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/duonera_discovery_profiles`,{method:'POST',headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Accept:'application/json','Content-Type':'application/json'},body:'{}'});if(!response.ok)throw new Error('Výběr se nepodařilo načíst.');return response.json()}
function renderProfile(){if(!ownProfile){profileRoot.querySelector('[data-profile-name]').textContent=auth.user.email||'DUONERA';return}profileRoot.querySelector('[data-profile-name]').textContent=`${ownProfile.first_name||'DUONERA'}, ${ownProfile.birth_date?calculateAge(ownProfile.birth_date):'—'}`;profileRoot.querySelector('[data-profile-location]').textContent=[ownProfile.city,ownProfile.country].filter(Boolean).join(', ');profileRoot.querySelector('[data-profile-seeking]').textContent=ownProfile.looking_for||'—';profileRoot.querySelector('[data-profile-languages]').textContent=Array.isArray(ownProfile.languages)?ownProfile.languages.join(', '):'—';profileRoot.querySelector('[data-profile-distance]').textContent=`${ownProfile.preferred_distance_km||50} km`;profileRoot.querySelector('.profile-avatar').textContent=String(ownProfile.first_name||'D').charAt(0).toUpperCase()}
function calculateAge(value){const birth=new Date(`${value}T00:00:00`);const now=new Date();let age=now.getFullYear()-birth.getFullYear();const month=now.getMonth()-birth.getMonth();if(month<0||(month===0&&now.getDate()<birth.getDate()))age--;return age}
async function loadApp(){notice.textContent='Načítáme váš soukromý výběr…';document.querySelector('[data-member-email]').textContent=auth.user.email||'';try{await callMemberRpc('duonera_claim_registration').catch(()=>{});const[ownRows,discovery,myChoices]=await Promise.all([memberRest(`duonera_profiles?select=*&user_id=eq.${encodeURIComponent(auth.user.id)}&limit=1`),fetchDiscovery(),callMemberRpc('duonera_my_choices')]);ownProfile=ownRows?.[0]||null;choices=new Map((myChoices||[]).map(choice=>[choice.chosen_profile_id,choice]));const visible=(discovery||[]).filter(profile=>profile.id!==ownProfile?.id).slice(0,3);candidatesRoot.replaceChildren();if(!visible.length){candidatesRoot.innerHTML='<div class="empty-state"><i>◇</i><h2>Výběr se připravuje</h2><p>Právě hledáme vhodné lidi ve vašem okruhu. Nezobrazujeme náhodné profily jen proto, aby stránka nebyla prázdná.</p></div>'}else visible.forEach((profile,index)=>candidatesRoot.append(candidateCard(profile,index)));updateVisibleCount();renderProfile();notice.textContent=ownProfile?'Profil je aktivní. Zobrazujeme pouze malý soukromý výběr.':'Dokončete svůj profil, aby mohl systém zpřesnit doporučení.'}catch(error){console.error(error);notice.textContent=error.message||'Účet se nepodařilo načíst.'}}
async function openApp(session){auth=session;authView.hidden=true;appView.hidden=false;logoutButton.hidden=false;await loadApp()}

loginForm.addEventListener('submit',async event=>{if(recoveryMode)return;event.preventDefault();const button=loginForm.querySelector('.gold-button');button.disabled=true;message(t('signingIn'));try{const data=new FormData(loginForm);await openApp(await signInMember(data.get('email'),data.get('password')))}catch(error){message(errorText(error),true)}finally{button.disabled=false}});
document.querySelector('[data-reset]').addEventListener('click',async()=>{const email=loginForm.elements.email.value.trim();if(!email){message(t('enterEmail'),true);loginForm.elements.email.focus();return}message(t('sendingReset'));try{await requestPasswordReset(email,`${location.origin}/v2-app.html?recovery=1`);message(t('resetSent'))}catch{message(t('resetFailed'),true)}});
logoutButton.addEventListener('click',async()=>{await signOutMember();location.href='v2-app.html'});
document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(item=>item.classList.toggle('active',item===button));document.querySelectorAll('[data-panel]').forEach(panel=>{panel.hidden=panel.dataset.panel!==button.dataset.tab})}));

async function showRecovery(){recoveryMode=true;authView.hidden=false;appView.hidden=true;logoutButton.hidden=true;loginForm.innerHTML=`<img src="assets/duonera-v2-mark.svg" alt=""><p>${t('newPasswordLabel')}</p><h2>${t('newPasswordTitle')}</h2><label><span>${t('newPassword')}</span><input name="password" type="password" minlength="8" autocomplete="new-password" required></label><label><span>${t('repeatPassword')}</span><input name="repeat" type="password" minlength="8" autocomplete="new-password" required></label><button class="gold-button" type="submit">${t('savePassword')} <b>→</b></button><div class="auth-message" data-recovery-message role="status"></div>`;loginForm.onsubmit=async event=>{event.preventDefault();const password=loginForm.elements.password.value;const output=loginForm.querySelector('[data-recovery-message]');if(password.length<8){output.textContent=t('passwordShort');output.classList.add('error');return}if(password!==loginForm.elements.repeat.value){output.textContent=t('passwordMismatch');output.classList.add('error');return}try{await updateMemberPassword(password);output.textContent=t('passwordSaved');const session=await requireMemberSession();if(session)await openApp(session)}catch{output.textContent=t('linkExpired');output.classList.add('error')}}}

(async()=>{const recovery=new URLSearchParams(location.search).get('recovery')==='1';const session=await requireMemberSession();if(recovery){await showRecovery();return}if(session)await openApp(session)})();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/service-worker.js').catch(error=>console.warn('PWA registration failed',error)));
