import { SUPABASE_PUBLISHABLE_KEY, SUPABASE_URL } from './supabase-client.js?v=24';
import { callMemberRpc, requestPasswordReset, requireMemberSession, signInMember, signOutMember, updateMemberPassword } from './member-auth.js?v=24';
import { ensureMemberProfile } from './member-bootstrap.js?v=24';
import { createMemberPhotoUrl } from './registration-photo.js?v=24';

const authView=document.querySelector('[data-auth-view]');
const appView=document.querySelector('[data-app-view]');
const loginForm=document.querySelector('[data-login-form]');
const authMessage=document.querySelector('[data-auth-message]');
const logoutButton=document.querySelector('[data-logout]');
const notice=document.querySelector('[data-notice]');
const candidatesRoot=document.querySelector('[data-candidates]');
const profileRoot=document.querySelector('[data-profile]');
const matchesPanel=document.querySelector('[data-panel="matches"]');
const messagesPanel=document.querySelector('[data-panel="messages"]');
const languageSelect=document.querySelector('[data-app-language]');
let auth=null;
let ownProfile=null;
let recommendations=[];
let recoveryMode=false;

const ui={
  cs:{home:'Domů',logout:'Odhlásit',privateAccess:'SOUKROMÝ PŘÍSTUP',yourSelection:'Váš výběr.',justForYou:'Jen pro vás.',privacyLine:'Žádný veřejný katalog. Kontakt až po vzájemném zájmu.',loginLabel:'PŘIHLÁŠENÍ',welcomeBack:'Vítejte zpět.',password:'Heslo',signIn:'Přihlásit se',forgot:'Zapomněli jste heslo?',noProfile:'Ještě nemáte profil?',createProfile:'Vytvořit soukromý profil',selectedForYou:'VYBRÁNO PRO VÁS',threeRecommendations:'Vaše tři doporučení.',ofThree:'z 3 dnes',forYou:'Pro vás',choices:'Volby',messages:'Zprávy',profile:'Profil'},
  en:{home:'Home',logout:'Sign out',privateAccess:'PRIVATE ACCESS',yourSelection:'Your selection.',justForYou:'Only for you.',privacyLine:'No public catalogue. Contact only after mutual interest.',loginLabel:'SIGN IN',welcomeBack:'Welcome back.',password:'Password',signIn:'Sign in',forgot:'Forgot your password?',noProfile:'No profile yet?',createProfile:'Create private profile',selectedForYou:'SELECTED FOR YOU',threeRecommendations:'Your three recommendations.',ofThree:'of 3 today',forYou:'For you',choices:'Choices',messages:'Messages',profile:'Profile'},
  ru:{home:'Главная',logout:'Выйти',privateAccess:'ПРИВАТНЫЙ ДОСТУП',yourSelection:'Ваша подборка.',justForYou:'Только для вас.',privacyLine:'Без публичного каталога. Контакт только после взаимного интереса.',loginLabel:'ВХОД',welcomeBack:'С возвращением.',password:'Пароль',signIn:'Войти',forgot:'Забыли пароль?',noProfile:'Ещё нет анкеты?',createProfile:'Создать приватный профиль',selectedForYou:'ВЫБРАНО ДЛЯ ВАС',threeRecommendations:'Ваши три рекомендации.',ofThree:'из 3 сегодня',forYou:'Для вас',choices:'Выбор',messages:'Сообщения',profile:'Профиль'}
};
let lang='cs';
function copy(){return ui[lang]||ui.cs}
function setLanguage(code){lang=ui[code]?code:'cs';document.documentElement.lang=lang;document.querySelectorAll('[data-app-i18n]').forEach(node=>{const value=copy()[node.dataset.appI18n];if(value)node.textContent=value});if(languageSelect)languageSelect.value=lang;try{localStorage.setItem('duonera-lang',lang)}catch{}}
try{setLanguage(localStorage.getItem('duonera-lang')||'cs')}catch{setLanguage('cs')}
languageSelect?.addEventListener('change',event=>setLanguage(event.target.value));

function showMessage(text='',error=false){if(!authMessage)return;authMessage.textContent=text;authMessage.classList.toggle('error',error)}
function setNotice(text,tone=''){if(!notice)return;notice.textContent=text;notice.dataset.tone=tone}
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function canonical(value){const s=String(value||'').trim().toLowerCase();if(['žena','ženu','female','woman','frau','donna','kobieta','женщина','женщину','жінка','жінку'].includes(s))return'female';if(['muž','muže','male','man','mann','uomo','mężczyzna','мужчина','мужчину','чоловік','чоловіка'].includes(s))return'male';return s}
function profileAge(profile){if(Number.isFinite(Number(profile.age)))return Number(profile.age);if(!profile.birth_date)return'—';const birth=new Date(`${profile.birth_date}T00:00:00`);const now=new Date();let age=now.getFullYear()-birth.getFullYear();const m=now.getMonth()-birth.getMonth();if(m<0||(m===0&&now.getDate()<birth.getDate()))age--;return age}
function publicPhotoUrl(path){if(!path)return'';return`${SUPABASE_URL}/storage/v1/object/public/duonera-discovery-photos/${String(path).split('/').map(encodeURIComponent).join('/')}`}
function firstPhoto(profile){const list=Array.isArray(profile.public_photo_paths)?profile.public_photo_paths:[];return list[0]?publicPhotoUrl(list[0]):''}
function reasons(profile){const out=[];if(profile.selection_note)out.push(profile.selection_note);if(profile.distance_km!=null)out.push(`${profile.distance_km} km od vás`);else if(profile.same_city)out.push('Stejné město');else if(profile.same_country)out.push('Stejná země');if(Array.isArray(profile.shared_interests)&&profile.shared_interests.length)out.push(`Společné zájmy: ${profile.shared_interests.slice(0,2).join(', ')}`);if(Array.isArray(profile.shared_languages)&&profile.shared_languages.length)out.push(`Společný jazyk: ${profile.shared_languages.slice(0,2).join(', ')}`);if(profile.same_goal)out.push('Podobný cíl vztahu');return out.slice(0,3)}

async function legacyDiscovery(){const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/duonera_discovery_profiles`,{method:'POST',headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Accept:'application/json','Content-Type':'application/json'},body:'{}'});if(!response.ok)return[];const rows=await response.json();const wanted=canonical(ownProfile?.looking_for);const city=String(ownProfile?.city||'').trim().toLowerCase();const country=String(ownProfile?.country||'').trim().toLowerCase();return(rows||[]).filter(p=>!wanted||canonical(p.gender)===wanted).map(p=>({...p,profile_id:p.id,same_city:String(p.city||'').trim().toLowerCase()===city,same_country:String(p.country||'').trim().toLowerCase()===country,match_score:(String(p.city||'').trim().toLowerCase()===city?78:String(p.country||'').trim().toLowerCase()===country?68:58)})).sort((a,b)=>b.match_score-a.match_score).slice(0,3)}
async function loadRecommendations(){try{return await callMemberRpc('duonera_recommendations')||[]}catch(error){console.warn('DUONERA recommendation RPC is not active yet; using compatibility fallback.',error);return legacyDiscovery()}}

function card(profile,index){const article=document.createElement('article');article.className='candidate';const id=profile.profile_id||profile.id;article.dataset.profileId=id;const photo=firstPhoto(profile);const why=reasons(profile);article.innerHTML=`<div class="candidate-photo"><span class="candidate-index">${index+1} / ${recommendations.length}</span>${profile.match_score?`<span class="verified">${escapeHtml(profile.match_score)}%</span>`:''}</div><div class="candidate-body"><h2>${escapeHtml(profile.first_name||'DUONERA')}, ${profileAge(profile)}</h2><p class="location">${escapeHtml([profile.city,profile.country].filter(Boolean).join(', '))}</p><p class="about">${escapeHtml(profile.about_me||profile.relationship_goal||'Vážný vztah a skutečné setkání.')}</p>${why.length?`<div class="tags">${why.map(item=>`<span>${escapeHtml(item)}</span>`).join('')}</div>`:''}<div class="candidate-actions"><button class="pass" type="button" aria-label="Přeskočit">×</button><button class="interest" type="button">Mám zájem</button></div></div>`;if(photo)article.querySelector('.candidate-photo').style.backgroundImage=`url("${photo}")`;article.querySelector('.interest').addEventListener('click',async()=>{const button=article.querySelector('.interest');button.disabled=true;try{const result=await callMemberRpc('duonera_choose_profile',{target_profile_id:id});button.textContent=result?.mutual?'Je to vzájemné':'Zájem odeslán';button.classList.add(result?.mutual?'mutual':'selected');setNotice(result?.mutual?'Vzájemná volba — můžete si napsat.':'Váš zájem je uložen.','success');await renderRelationships()}catch(error){setNotice(error.message||'Volbu se nepodařilo uložit.','error');button.disabled=false}});article.querySelector('.pass').addEventListener('click',async()=>{const buttons=article.querySelectorAll('button');buttons.forEach(b=>b.disabled=true);try{await callMemberRpc('duonera_pass_profile',{target_profile_id:id})}catch(error){console.warn('Pass persistence is not active yet.',error)}article.remove();updateCount();setNotice('Profil přeskočen. Systém ho nebude znovu nabízet po aktivaci nové databázové logiky.');});return article}
function updateCount(){const count=candidatesRoot.querySelectorAll('.candidate').length;document.querySelector('[data-count]').textContent=String(count)}
function renderRecommendations(){candidatesRoot.replaceChildren();if(!recommendations.length){candidatesRoot.innerHTML='<div class="empty-state"><i>◇</i><h2>Výběr se připravuje</h2><p>Teď tu není vhodný profil. DUONERA neukazuje náhodné lidi jen proto, aby stránka nebyla prázdná.</p></div>'}else recommendations.forEach((profile,index)=>candidatesRoot.append(card(profile,index)));updateCount()}

async function renderRelationships(){if(matchesPanel){try{const choices=await callMemberRpc('duonera_my_choice_profiles');matchesPanel.innerHTML='<div class="empty-state"><i>♡</i><h2>Vaše volby</h2><p></p></div>';const root=matchesPanel.querySelector('p');root.innerHTML=(choices||[]).length?(choices||[]).map(p=>`${escapeHtml(p.first_name||'DUONERA')}, ${profileAge(p)} — ${p.is_mutual?'vzájemné':'čeká na odpověď'}`).join('<br>'):'Zatím jste nikoho nevybrali.'}catch{}}if(messagesPanel){try{const matches=await callMemberRpc('duonera_my_matches');messagesPanel.innerHTML='<div class="empty-state"><i>▤</i><h2>Soukromé zprávy</h2><p></p></div>';messagesPanel.querySelector('p').innerHTML=(matches||[]).length?(matches||[]).map(p=>`${escapeHtml(p.first_name||'DUONERA')}, ${profileAge(p)} — chat je otevřen`).join('<br>'):'Chat se otevře až po vzájemném výběru.'}catch{}}}

async function renderProfile(){const avatar=profileRoot?.querySelector('.profile-avatar');if(!profileRoot||!avatar)return;avatar.textContent='D';avatar.style.backgroundImage='';if(!ownProfile){profileRoot.querySelector('[data-profile-name]').textContent=auth?.user?.email||'DUONERA';return}profileRoot.querySelector('[data-profile-name]').textContent=`${ownProfile.first_name||'DUONERA'}, ${profileAge(ownProfile)}`;profileRoot.querySelector('[data-profile-location]').textContent=[ownProfile.city,ownProfile.country].filter(Boolean).join(', ');profileRoot.querySelector('[data-profile-seeking]').textContent=ownProfile.looking_for||'—';profileRoot.querySelector('[data-profile-languages]').textContent=Array.isArray(ownProfile.languages)?ownProfile.languages.join(', '):'—';profileRoot.querySelector('[data-profile-distance]').textContent=`${ownProfile.preferred_distance_km||50} km`;avatar.textContent=String(ownProfile.first_name||'D').charAt(0).toUpperCase();const publicPath=Array.isArray(ownProfile.public_photo_paths)?ownProfile.public_photo_paths[0]:'';const privatePath=Array.isArray(ownProfile.photo_paths)?ownProfile.photo_paths[0]:'';const url=publicPath?publicPhotoUrl(publicPath):await createMemberPhotoUrl(auth,privatePath);if(url){avatar.style.backgroundImage=`url("${url}")`;avatar.style.backgroundSize='cover';avatar.style.backgroundPosition='center';avatar.textContent=''}}

async function loadApp(){setNotice('Načítáme váš soukromý výběr…');document.querySelector('[data-member-email]').textContent=auth.user.email||'';try{ownProfile=await ensureMemberProfile(auth);if(ownProfile)await callMemberRpc('duonera_touch_profile').catch(()=>{});recommendations=await loadRecommendations();renderRecommendations();await Promise.all([renderProfile(),renderRelationships()]);setNotice(ownProfile?'Profil je připraven. Systém vybírá jen několik vhodných lidí.':'Registrace je uložená, profil se právě vytváří.')}catch(error){console.error(error);setNotice(error.message||'Účet se nepodařilo načíst.','error')}}
async function openApp(session){auth=session;authView.hidden=true;appView.hidden=false;logoutButton.hidden=false;await loadApp()}

loginForm.addEventListener('submit',async event=>{if(recoveryMode)return;event.preventDefault();const button=loginForm.querySelector('.gold-button');button.disabled=true;showMessage('Přihlašujeme…');try{const data=new FormData(loginForm);await openApp(await signInMember(data.get('email'),data.get('password')))}catch(error){const msg=String(error?.message||'').toLowerCase();showMessage(msg.includes('email not confirmed')?'Nejdříve potvrďte e-mail.':'Nesprávný e-mail nebo heslo.',true)}finally{button.disabled=false}});
document.querySelector('[data-reset]')?.addEventListener('click',async()=>{const email=loginForm.elements.email.value.trim();if(!email){showMessage('Nejdříve zadejte e-mail.',true);return}showMessage('Odesíláme odkaz…');try{await requestPasswordReset(email,`${location.origin}/v2-app.html?recovery=1`);showMessage('Odkaz pro nové heslo jsme poslali na e-mail.')}catch{showMessage('Odkaz se nepodařilo odeslat.',true)}});
logoutButton.addEventListener('click',async()=>{await signOutMember();location.href='v2-app.html'});
document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(item=>item.classList.toggle('active',item===button));document.querySelectorAll('[data-panel]').forEach(panel=>panel.hidden=panel.dataset.panel!==button.dataset.tab)}));

async function showRecovery(){recoveryMode=true;loginForm.innerHTML='<img src="assets/duonera-v2-mark.svg" alt=""><p>NOVÉ HESLO</p><h2>Nastavte nové heslo.</h2><label><span>Nové heslo</span><input name="password" type="password" minlength="8" required></label><label><span>Zopakujte heslo</span><input name="repeat" type="password" minlength="8" required></label><button class="gold-button" type="submit">Uložit heslo <b>→</b></button><div class="auth-message" data-recovery-message></div>';loginForm.onsubmit=async event=>{event.preventDefault();const p=loginForm.elements.password.value;const out=loginForm.querySelector('[data-recovery-message]');if(p.length<8||p!==loginForm.elements.repeat.value){out.textContent='Hesla musí mít alespoň 8 znaků a shodovat se.';return}try{await updateMemberPassword(p);const session=await requireMemberSession();if(session)await openApp(session)}catch{out.textContent='Odkaz už není platný. Pošlete si nový.'}}}

(async()=>{const params=new URLSearchParams(location.search);const email=params.get('email')||'';if(email&&loginForm.elements.email)loginForm.elements.email.value=email;const session=await requireMemberSession();if(params.get('recovery')==='1'){await showRecovery();return}if(session)await openApp(session)})();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/service-worker.js').catch(()=>{}));
