import { createUuid, insertRow } from './supabase-client.js?v=5';
import { registerMember } from './member-auth.js?v=19';
import { compressProfilePhoto, savePendingRegistrationPhoto } from './registration-photo.js?v=1';

const cs={login:'Přihlásit se',eyebrow:'SOUKROMÉ SEZNÁMENÍ VE VAŠEM MĚSTĚ',headline:'Někdo blízký.',headlineAccent:'Ne další profil.',lead:'Tři pečlivě vybraní lidé poblíž. Kontakt se otevře jen při vzájemném zájmu.',nearby:'lidé poblíž dnes',proofOne:'doporučení pro vás',proofTwo:'veřejných profilů',proofThree:'skutečný cíl',cta:'Najít mé tři',private:'Diskrétně',minute:'1 minuta',verified:'Ověřené profily',how:'JAK TO',works:'FUNGUJE',step1:'Vytvoříte profil',step1s:'Jen to důležité',step2:'Dostanete 3 lidi',step2s:'Žádné nekonečné listování',step3:'Vzájemné ano',step3s:'Kontakt se otevře oběma',step4:'Skutečné setkání',step4s:'Soukromě a bezpečně',formEyebrow:'VÁŠ SOUKROMÝ VSTUP',formTitle:'Začněte jednou minutou.',iam:'Jsem',seeking:'Hledám',woman:'Žena',man:'Muž',seekWoman:'Ženu',seekMan:'Muže',name:'Jméno',age:'Věk',city:'Město',distance:'Vzdálenost',photo:'Přidat fotografii',photoHint:'Aktuální fotografie obličeje',password:'Heslo',consent:'Souhlasím se zpracováním údajů pro registraci a soukromý výběr.',privacyLink:'Soukromí',submit:'Vytvořit soukromý profil',formFoot:'Zdarma · bez předplatného · od 18 let',successEyebrow:'VÍTEJTE V DUONERA',success:'Váš soukromý profil je připraven,',successText:'Potvrďte e-mail. Potom se otevře váš osobní výběr.',openAccount:'Otevřít můj účet',photoAlt:'Dva lidé se potkávají ve večerním evropském městě',invalid:'Doplňte označené údaje.',photoInvalid:'Vyberte fotografii JPG, PNG nebo WEBP do 12 MB.',submitting:'Vytvářím profil…',accountExists:'Tento e-mail už má účet. Přihlaste se.',error:'Registraci se nepodařilo dokončit. Zkuste to znovu.'};
const copy={
  cs,
  en:{...cs,login:'Sign in',eyebrow:'PRIVATE INTRODUCTIONS IN YOUR CITY',headline:'Someone nearby.',headlineAccent:'Not another profile.',lead:'Three carefully selected people nearby. Contact opens only after mutual interest.',nearby:'people nearby today',proofOne:'recommendations for you',proofTwo:'public profiles',proofThree:'real goal',cta:'Find my three',private:'Discreet',minute:'1 minute',verified:'Verified profiles',how:'HOW IT',works:'WORKS',step1:'Create a profile',step1s:'Only what matters',step2:'Receive 3 people',step2s:'No endless browsing',step3:'Mutual yes',step3s:'Contact opens for both',step4:'A real meeting',step4s:'Private and safe',formEyebrow:'YOUR PRIVATE ENTRY',formTitle:'Start with one minute.',iam:'I am',seeking:'Looking for',woman:'Woman',man:'Man',seekWoman:'Woman',seekMan:'Man',name:'Name',age:'Age',city:'City',distance:'Distance',photo:'Add your photo',photoHint:'A recent clear portrait',password:'Password',consent:'I agree to data processing for registration and private matching.',privacyLink:'Privacy',submit:'Create private profile',formFoot:'Free · no subscription · 18+',successEyebrow:'WELCOME TO DUONERA',success:'Your private profile is ready,',successText:'Confirm your email. Your personal selection will then open.',openAccount:'Open my account',invalid:'Complete the highlighted details.',photoInvalid:'Choose a JPG, PNG or WEBP photo up to 12 MB.',submitting:'Creating profile…',accountExists:'This email already has an account. Sign in.',error:'Registration could not be completed. Please try again.'},
  de:{...cs,login:'Anmelden',eyebrow:'PRIVATE BEGEGNUNGEN IN IHRER STADT',headline:'Jemand in Ihrer Nähe.',headlineAccent:'Nicht noch ein Profil.',lead:'Drei sorgfältig ausgewählte Menschen in Ihrer Nähe. Kontakt gibt es nur bei gegenseitigem Interesse.',nearby:'Menschen heute in der Nähe',proofOne:'Empfehlungen für Sie',proofTwo:'öffentliche Profile',proofThree:'echtes Ziel',cta:'Meine drei finden',private:'Diskret',minute:'1 Minute',verified:'Geprüfte Profile',how:'SO',works:'FUNKTIONIERT ES',step1:'Profil erstellen',step1s:'Nur das Wesentliche',step2:'3 Menschen erhalten',step2s:'Kein endloses Suchen',step3:'Gegenseitiges Ja',step3s:'Kontakt öffnet sich für beide',step4:'Echtes Treffen',step4s:'Privat und sicher',formEyebrow:'IHR PRIVATER EINSTIEG',formTitle:'Beginnen Sie mit einer Minute.',iam:'Ich bin',seeking:'Ich suche',woman:'Frau',man:'Mann',seekWoman:'Frau',seekMan:'Mann',name:'Name',age:'Alter',city:'Stadt',distance:'Entfernung',photo:'Foto hinzufügen',photoHint:'Aktuelles, klares Porträt',password:'Passwort',consent:'Ich stimme der Datenverarbeitung für Registrierung und private Auswahl zu.',privacyLink:'Datenschutz',submit:'Privates Profil erstellen',formFoot:'Kostenlos · kein Abo · ab 18',successEyebrow:'WILLKOMMEN BEI DUONERA',success:'Ihr privates Profil ist bereit,',successText:'Bestätigen Sie Ihre E-Mail. Danach öffnet sich Ihre persönliche Auswahl.',openAccount:'Mein Konto öffnen',invalid:'Ergänzen Sie die markierten Angaben.',photoInvalid:'Wählen Sie ein JPG-, PNG- oder WEBP-Foto bis 12 MB.',submitting:'Profil wird erstellt…',accountExists:'Für diese E-Mail besteht bereits ein Konto. Melden Sie sich an.',error:'Die Registrierung konnte nicht abgeschlossen werden.'},
  it:{...cs,login:'Accedi',eyebrow:'INCONTRI PRIVATI NELLA TUA CITTÀ',headline:'Qualcuno vicino.',headlineAccent:'Non un altro profilo.',lead:'Tre persone vicine scelte con cura. Il contatto si apre solo con interesse reciproco.',nearby:'persone vicine oggi',proofOne:'proposte per te',proofTwo:'profili pubblici',proofThree:'obiettivo reale',cta:'Trova i miei tre',private:'Riservato',minute:'1 minuto',verified:'Profili verificati',how:'COME',works:'FUNZIONA',step1:'Crea il profilo',step1s:'Solo ciò che conta',step2:'Ricevi 3 persone',step2s:'Nessuna ricerca infinita',step3:'Scelta reciproca',step3s:'Il contatto si apre per entrambi',step4:'Un incontro reale',step4s:'Privato e sicuro',formEyebrow:'IL TUO INGRESSO PRIVATO',formTitle:'Inizia con un minuto.',iam:'Sono',seeking:'Cerco',woman:'Donna',man:'Uomo',seekWoman:'Donna',seekMan:'Uomo',name:'Nome',age:'Età',city:'Città',distance:'Distanza',photo:'Aggiungi foto',photoHint:'Ritratto recente e nitido',password:'Password',consent:'Acconsento al trattamento dei dati per registrazione e selezione privata.',privacyLink:'Privacy',submit:'Crea profilo privato',formFoot:'Gratis · nessun abbonamento · 18+',successEyebrow:'BENVENUTO IN DUONERA',success:'Il tuo profilo privato è pronto,',successText:'Conferma l’e-mail. Poi si aprirà la tua selezione personale.',openAccount:'Apri il mio account',invalid:'Completa i dati evidenziati.',photoInvalid:'Scegli una foto JPG, PNG o WEBP fino a 12 MB.',submitting:'Creazione profilo…',accountExists:'Questa e-mail ha già un account. Accedi.',error:'Impossibile completare la registrazione.'},
  pl:{...cs,login:'Zaloguj się',eyebrow:'PRYWATNE POZNANIE W TWOIM MIEŚCIE',headline:'Ktoś blisko.',headlineAccent:'Nie kolejny profil.',lead:'Trzy starannie wybrane osoby w pobliżu. Kontakt otworzy się tylko po wzajemnym zainteresowaniu.',nearby:'osoby w pobliżu dziś',proofOne:'propozycje dla Ciebie',proofTwo:'publicznych profili',proofThree:'prawdziwy cel',cta:'Znajdź moją trójkę',private:'Dyskretnie',minute:'1 minuta',verified:'Zweryfikowane profile',how:'JAK TO',works:'DZIAŁA',step1:'Utwórz profil',step1s:'Tylko to, co ważne',step2:'Otrzymaj 3 osoby',step2s:'Bez niekończącego się przeglądania',step3:'Wzajemne tak',step3s:'Kontakt otwiera się dla obojga',step4:'Prawdziwe spotkanie',step4s:'Prywatnie i bezpiecznie',formEyebrow:'TWÓJ PRYWATNY START',formTitle:'Zacznij od jednej minuty.',iam:'Jestem',seeking:'Szukam',woman:'Kobieta',man:'Mężczyzna',seekWoman:'Kobiety',seekMan:'Mężczyzny',name:'Imię',age:'Wiek',city:'Miasto',distance:'Odległość',photo:'Dodaj zdjęcie',photoHint:'Aktualny wyraźny portret',password:'Hasło',consent:'Zgadzam się na przetwarzanie danych do rejestracji i prywatnego doboru.',privacyLink:'Prywatność',submit:'Utwórz prywatny profil',formFoot:'Bezpłatnie · bez abonamentu · 18+',successEyebrow:'WITAMY W DUONERA',success:'Twój prywatny profil jest gotowy,',successText:'Potwierdź e-mail. Potem otworzy się Twój osobisty wybór.',openAccount:'Otwórz moje konto',invalid:'Uzupełnij zaznaczone dane.',photoInvalid:'Wybierz zdjęcie JPG, PNG lub WEBP do 12 MB.',submitting:'Tworzenie profilu…',accountExists:'Dla tego e-maila istnieje już konto. Zaloguj się.',error:'Nie udało się ukończyć rejestracji.'},
  sk:{...cs,login:'Prihlásiť sa',eyebrow:'SÚKROMNÉ ZOZNÁMENIE VO VAŠOM MESTE',headline:'Niekto nablízku.',headlineAccent:'Nie ďalší profil.',lead:'Traja starostlivo vybraní ľudia nablízku. Kontakt sa otvorí iba pri vzájomnom záujme.',nearby:'ľudia nablízku dnes',proofOne:'odporúčania pre vás',proofTwo:'verejných profilov',proofThree:'skutočný cieľ',cta:'Nájsť mojich troch',private:'Diskrétne',minute:'1 minúta',verified:'Overené profily',how:'AKO TO',works:'FUNGUJE',step1:'Vytvoríte profil',step1s:'Len to dôležité',step2:'Dostanete 3 ľudí',step2s:'Žiadne nekonečné listovanie',step3:'Vzájomné áno',step3s:'Kontakt sa otvorí obom',step4:'Skutočné stretnutie',step4s:'Súkromne a bezpečne',formEyebrow:'VÁŠ SÚKROMNÝ VSTUP',formTitle:'Začnite jednou minútou.',iam:'Som',seeking:'Hľadám',woman:'Žena',man:'Muž',seekWoman:'Ženu',seekMan:'Muža',name:'Meno',age:'Vek',city:'Mesto',distance:'Vzdialenosť',photo:'Pridať fotografiu',photoHint:'Aktuálny jasný portrét',password:'Heslo',consent:'Súhlasím so spracovaním údajov na registráciu a súkromný výber.',privacyLink:'Súkromie',submit:'Vytvoriť súkromný profil',formFoot:'Zadarmo · bez predplatného · od 18',successEyebrow:'VITAJTE V DUONERA',success:'Váš súkromný profil je pripravený,',successText:'Potvrďte e-mail. Potom sa otvorí váš osobný výber.',openAccount:'Otvoriť môj účet',invalid:'Doplňte označené údaje.',photoInvalid:'Vyberte fotografiu JPG, PNG alebo WEBP do 12 MB.',submitting:'Vytváram profil…',accountExists:'Tento e-mail už má účet. Prihláste sa.',error:'Registráciu sa nepodarilo dokončiť.'},
  uk:{...cs,login:'Увійти',eyebrow:'ПРИВАТНІ ЗНАЙОМСТВА У ВАШОМУ МІСТІ',headline:'Хтось поруч.',headlineAccent:'Не ще одна анкета.',lead:'Три ретельно підібрані людини поруч. Контакт відкриється лише за взаємного інтересу.',nearby:'люди поруч сьогодні',proofOne:'рекомендації для вас',proofTwo:'публічних анкет',proofThree:'справжня мета',cta:'Знайти мою трійку',private:'Конфіденційно',minute:'1 хвилина',verified:'Перевірені анкети',how:'ЯК ЦЕ',works:'ПРАЦЮЄ',step1:'Створіть анкету',step1s:'Лише важливе',step2:'Отримайте 3 людей',step2s:'Без нескінченного перегляду',step3:'Взаємне так',step3s:'Контакт відкриється обом',step4:'Справжня зустріч',step4s:'Приватно й безпечно',formEyebrow:'ВАШ ПРИВАТНИЙ ВХІД',formTitle:'Почніть з однієї хвилини.',iam:'Я',seeking:'Шукаю',woman:'Жінка',man:'Чоловік',seekWoman:'Жінку',seekMan:'Чоловіка',name:'Ім’я',age:'Вік',city:'Місто',distance:'Відстань',photo:'Додати фотографію',photoHint:'Актуальний чіткий портрет',password:'Пароль',consent:'Я погоджуюся на обробку даних для реєстрації та приватного добору.',privacyLink:'Конфіденційність',submit:'Створити приватну анкету',formFoot:'Безкоштовно · без підписки · 18+',successEyebrow:'ВІТАЄМО В DUONERA',success:'Ваша приватна анкета готова,',successText:'Підтвердьте e-mail. Після цього відкриється ваша персональна добірка.',openAccount:'Відкрити мій кабінет',invalid:'Заповніть позначені дані.',photoInvalid:'Оберіть фото JPG, PNG або WEBP до 12 МБ.',submitting:'Створюємо анкету…',accountExists:'Для цього e-mail уже є обліковий запис. Увійдіть.',error:'Не вдалося завершити реєстрацію.'},
  ru:{...cs,login:'Войти',eyebrow:'ПРИВАТНЫЕ ЗНАКОМСТВА В ВАШЕМ ГОРОДЕ',headline:'Кто-то рядом.',headlineAccent:'Не ещё одна анкета.',lead:'Три тщательно подобранных человека рядом. Контакт откроется только при взаимном интересе.',nearby:'люди рядом сегодня',proofOne:'рекомендации для вас',proofTwo:'публичных анкет',proofThree:'настоящая цель',cta:'Найти мою тройку',private:'Конфиденциально',minute:'1 минута',verified:'Проверенные анкеты',how:'КАК ЭТО',works:'РАБОТАЕТ',step1:'Создайте анкету',step1s:'Только самое важное',step2:'Получите 3 человека',step2s:'Без бесконечного просмотра',step3:'Взаимное да',step3s:'Контакт откроется обоим',step4:'Настоящая встреча',step4s:'Приватно и безопасно',formEyebrow:'ВАШ ПРИВАТНЫЙ ВХОД',formTitle:'Начните с одной минуты.',iam:'Я',seeking:'Ищу',woman:'Женщина',man:'Мужчина',seekWoman:'Женщину',seekMan:'Мужчину',name:'Имя',age:'Возраст',city:'Город',distance:'Расстояние',photo:'Добавить фотографию',photoHint:'Актуальный чёткий портрет',password:'Пароль',consent:'Я согласен на обработку данных для регистрации и приватного подбора.',privacyLink:'Конфиденциальность',submit:'Создать приватную анкету',formFoot:'Бесплатно · без подписки · 18+',successEyebrow:'ДОБРО ПОЖАЛОВАТЬ В DUONERA',success:'Ваша приватная анкета готова,',successText:'Подтвердите e-mail. После этого откроется ваша персональная подборка.',openAccount:'Открыть мой кабинет',invalid:'Заполните отмеченные данные.',photoInvalid:'Выберите фото JPG, PNG или WEBP до 12 МБ.',submitting:'Создаём анкету…',accountExists:'Для этого e-mail уже есть аккаунт. Войдите.',error:'Не удалось завершить регистрацию.'}
};

const locale={cs:{country:'Česko',city:'Praha',language:'Čeština'},de:{country:'Deutschland',city:'Berlin',language:'Deutsch'},it:{country:'Italia',city:'Roma',language:'Italiano'},pl:{country:'Polska',city:'Warszawa',language:'Polski'},sk:{country:'Slovensko',city:'Bratislava',language:'Slovenčina'},uk:{country:'Україна',city:'Київ',language:'Українська'},ru:{country:'Česko',city:'Praha',language:'Русский'},en:{country:'Europe',city:'London',language:'English'}};
const aliases={cs:'cs',cz:'cs',de:'de',it:'it',pl:'pl',sk:'sk',uk:'uk',ua:'uk',ru:'ru',en:'en'};
const zones={'Europe/Prague':'cs','Europe/Berlin':'de','Europe/Vienna':'de','Europe/Rome':'it','Europe/Warsaw':'pl','Europe/Bratislava':'sk','Europe/Kyiv':'uk'};
const countryLanguage={CZ:'cs',DE:'de',AT:'de',CH:'de',IT:'it',PL:'pl',SK:'sk',UA:'uk'};
const countrySettings={CZ:{country:'Česko',city:'Praha'},DE:{country:'Deutschland',city:'Berlin'},AT:{country:'Österreich',city:'Wien'},CH:{country:'Schweiz',city:'Zürich'},IT:{country:'Italia',city:'Roma'},PL:{country:'Polska',city:'Warszawa'},SK:{country:'Slovensko',city:'Bratislava'},UA:{country:'Україна',city:'Київ'}};
const formCopy={cs:{name:'Jana',email:'vas@email.cz',password:'Min. 8 znaků',close:'Zavřít',cookie:'Pomozte nám měřit, zda DUONERA funguje. Reklamní měření spustíme jen s vaším souhlasem.',privacy:'Soukromí',reject:'Jen nutné',accept:'Povolit měření'},de:{name:'Anna',email:'ihre@email.de',password:'Mind. 8 Zeichen',close:'Schließen',cookie:'Helfen Sie uns zu messen, ob DUONERA funktioniert. Werbemessung startet nur mit Ihrer Zustimmung.',privacy:'Datenschutz',reject:'Nur erforderlich',accept:'Messung erlauben'},it:{name:'Giulia',email:'tua@email.it',password:'Min. 8 caratteri',close:'Chiudi',cookie:'Aiutaci a misurare l’efficacia di DUONERA. La misurazione pubblicitaria inizierà solo con il tuo consenso.',privacy:'Privacy',reject:'Solo necessari',accept:'Consenti misurazione'},pl:{name:'Anna',email:'twoj@email.pl',password:'Min. 8 znaków',close:'Zamknij',cookie:'Pomóż nam mierzyć skuteczność DUONERA. Pomiar reklam uruchomimy tylko za Twoją zgodą.',privacy:'Prywatność',reject:'Tylko niezbędne',accept:'Zezwól na pomiar'},sk:{name:'Jana',email:'vas@email.sk',password:'Min. 8 znakov',close:'Zavrieť',cookie:'Pomôžte nám merať, či DUONERA funguje. Meranie reklamy spustíme iba s vaším súhlasom.',privacy:'Súkromie',reject:'Iba nevyhnutné',accept:'Povoliť meranie'},uk:{name:'Анна',email:'vas@email.ua',password:'Мін. 8 символів',close:'Закрити',cookie:'Допоможіть нам виміряти ефективність DUONERA. Рекламне вимірювання почнеться лише з вашої згоди.',privacy:'Конфіденційність',reject:'Лише необхідні',accept:'Дозволити вимірювання'},ru:{name:'Анна',email:'vas@email.cz',password:'Мин. 8 символов',close:'Закрыть',cookie:'Помогите нам измерять эффективность DUONERA. Рекламное измерение начнётся только с вашего согласия.',privacy:'Конфиденциальность',reject:'Только необходимые',accept:'Разрешить измерение'},en:{name:'Anna',email:'you@email.com',password:'Min. 8 characters',close:'Close',cookie:'Help us measure whether DUONERA works. Advertising measurement starts only with your consent.',privacy:'Privacy',reject:'Essential only',accept:'Allow measurement'}};
const entryParams=new URLSearchParams(location.search);
const entryCountry=String(entryParams.get('country')||'').toUpperCase();
const explicitCity=entryParams.get('city')?.trim()||'';
let active='cs';
function initialLanguage(){const query=aliases[entryParams.get('lang')?.toLowerCase()];if(query)return query;if(countryLanguage[entryCountry])return countryLanguage[entryCountry];try{const saved=aliases[localStorage.getItem('duonera-lang')];if(saved)return saved}catch{}const zone=Intl.DateTimeFormat().resolvedOptions().timeZone;if(zones[zone])return zones[zone];for(const value of navigator.languages||[navigator.language]){const code=aliases[String(value).toLowerCase().split('-')[0]];if(code)return code}return'cs'}
function applyLanguage(code){active=copy[code]?code:'cs';document.documentElement.lang=active==='uk'?'uk':active;const text=copy[active];const extra=formCopy[active];const city=explicitCity||countrySettings[entryCountry]?.city||locale[active].city;document.querySelectorAll('[data-i18n]').forEach(node=>{if(text[node.dataset.i18n])node.textContent=text[node.dataset.i18n]});document.querySelectorAll('[data-i18n-aria]').forEach(node=>{if(text[node.dataset.i18nAria])node.setAttribute('aria-label',text[node.dataset.i18nAria])});document.querySelectorAll('[data-city]').forEach(node=>node.textContent=city);const cityInput=document.querySelector('[name="city"]');if(cityInput&&!cityInput.value)cityInput.value=city;document.querySelector('[name="first_name"]').placeholder=extra.name;cityInput.placeholder=city;document.querySelector('[name="email"]').placeholder=extra.email;document.querySelector('[name="password"]').placeholder=extra.password;document.querySelector('[data-close-register]').setAttribute('aria-label',extra.close);document.querySelector('[data-tracking-copy]').textContent=extra.cookie;document.querySelector('.tracking-consent a').textContent=extra.privacy;document.querySelector('[data-tracking-reject]').textContent=extra.reject;document.querySelector('[data-tracking-accept]').textContent=extra.accept;document.querySelector('[data-language]').value=active;try{localStorage.setItem('duonera-lang',active)}catch{}dispatchEvent(new CustomEvent('duonera-language-change',{detail:{language:active}}))}
document.querySelector('[data-language]').addEventListener('change',event=>applyLanguage(event.target.value));applyLanguage(initialLanguage());

const dialog=document.querySelector('.register-dialog');
const form=document.querySelector('.register-form');
const toast=document.querySelector('.toast');
document.querySelectorAll('[data-open-register]').forEach(button=>button.addEventListener('click',()=>dialog.showModal()));
document.querySelector('[data-close-register]').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(window.__v2toast);window.__v2toast=setTimeout(()=>toast.classList.remove('show'),3600)}
function markInvalid(){form.querySelectorAll('.invalid').forEach(node=>node.classList.remove('invalid'));const invalid=[...form.elements].filter(node=>node.willValidate&&!node.checkValidity());invalid.forEach(node=>(node.closest('fieldset')||node).classList.add('invalid'));if(invalid.length)invalid[0].focus();return invalid.length===0}

const photoInput=form.elements.photo;
const photoPreview=form.querySelector('[data-photo-preview]');
const photoPlaceholder=form.querySelector('[data-photo-placeholder]');
let preparedPhoto=null;
let photoUrl='';
let photoPreparation=Promise.resolve();
photoInput.addEventListener('change',()=>{photoPreparation=(async()=>{preparedPhoto=null;if(photoUrl)URL.revokeObjectURL(photoUrl);photoPreview.hidden=true;photoPlaceholder.hidden=false;const file=photoInput.files?.[0];if(!file)return;try{preparedPhoto=await compressProfilePhoto(file);photoUrl=URL.createObjectURL(preparedPhoto);photoPreview.src=photoUrl;photoPreview.hidden=false;photoPlaceholder.hidden=true}catch{photoInput.value='';showToast(copy[active].photoInvalid)}})()});
form.addEventListener('input',event=>{event.target.classList.remove('invalid');event.target.closest('fieldset')?.classList.remove('invalid')});
function gender(value){return value==='woman'?'Žena':'Muž'}
function seeking(value){return value==='woman'?'Ženu':'Muže'}
function trackRegistration(userId,profile){if(!userId)return;const gaKey=`duonera-sign-up-tracked:${userId}`;const metaKey=`duonera-meta-lead-tracked:${userId}`;try{if(typeof gtag==='function'&&!localStorage.getItem(gaKey)){localStorage.setItem(gaKey,'1');gtag('event','sign_up',{method:'email_password',landing_language:active,transport_type:'beacon'})}if(typeof fbq==='function'&&!localStorage.getItem(metaKey)){localStorage.setItem(metaKey,'1');fbq('track','Lead',{content_name:'duonera_registration',landing_language:active,campaign_source:profile.attribution.source,campaign_name:profile.attribution.campaign},{eventID:`duonera-sign-up-${userId}`})}}catch(error){console.warn('Registration measurement could not be completed',error)}}

const trackingConsent=document.querySelector('.tracking-consent');
const trackingChoice=()=>{try{return localStorage.getItem('duoneraConsentChoice')||localStorage.getItem('duoneraMarketingConsent')}catch{return null}};
if(trackingConsent&&!trackingChoice())trackingConsent.hidden=false;
document.querySelector('[data-tracking-reject]')?.addEventListener('click',()=>{try{localStorage.setItem('duoneraConsentChoice','necessary');localStorage.setItem('duoneraAnalyticsConsent','denied');localStorage.setItem('duoneraMarketingConsent','denied')}catch{}trackingConsent.hidden=true});
document.querySelector('[data-tracking-accept]')?.addEventListener('click',()=>{try{localStorage.setItem('duoneraConsentChoice','granted');localStorage.setItem('duoneraAnalyticsConsent','granted');localStorage.setItem('duoneraMarketingConsent','granted')}catch{}if(typeof gtag==='function')gtag('consent','update',{analytics_storage:'granted',ad_storage:'granted',ad_user_data:'granted',ad_personalization:'granted'});window.duoneraLoadMetaPixel?.();trackingConsent.hidden=true});

form.addEventListener('submit',async event=>{event.preventDefault();await photoPreparation;if(!markInvalid()){showToast(copy[active].invalid);return}if(!preparedPhoto){photoInput.classList.add('invalid');showToast(copy[active].photoInvalid);return}const data=new FormData(form);const id=createUuid();const params=new URLSearchParams(location.search);const profile={id,first_name:String(data.get('first_name')).trim(),age:Number(data.get('age')),gender:gender(data.get('gender')),looking_for:seeking(data.get('looking_for')),city:String(data.get('city')).trim(),country:countrySettings[entryCountry]?.country||locale[active].country,languages:[locale[active].language],email:String(data.get('email')).trim().toLowerCase(),preferred_distance_km:Number(data.get('distance')||50),consent_privacy:true,landing_language:active,attribution:{source:params.get('utm_source')||'direct',medium:params.get('utm_medium')||'',campaign:params.get('utm_campaign')||'',content:params.get('utm_content')||'',referrer:document.referrer||''},source:'duonera.cz/v2'};const button=form.querySelector('.submit');const label=button.querySelector('span');const original=label.textContent;const prototype=document.querySelector('meta[name="robots"]')?.content.includes('noindex');try{button.disabled=true;label.textContent=copy[active].submitting;let registration=null;if(prototype){await new Promise(resolve=>setTimeout(resolve,450))}else{await savePendingRegistrationPhoto(profile.email,preparedPhoto);registration=await registerMember(profile.email,String(data.get('password')||''),`${location.origin}/v2-app.html`,profile);try{await insertRow('duonera_leads',{id,gender:profile.gender,looking_for:profile.looking_for,age:profile.age,city:profile.city,email:profile.email,consent_privacy:true,source:profile.source},20000)}catch(error){console.warn('Lead row could not be saved',error)}}localStorage.setItem('duonera-short-registration',JSON.stringify(profile));localStorage.setItem('duonera-lead-id',id);if(!prototype&&registration?.user?.id)trackRegistration(registration.user.id,profile);document.querySelector('[data-success-name]').textContent=profile.first_name;const account=document.querySelector('[data-account-after-registration]');account.href=`v2-app.html?mode=login&email=${encodeURIComponent(profile.email)}`;dialog.close();document.querySelector('.success').hidden=false}catch(error){console.error(error);showToast(error?.code==='account_exists'?copy[active].accountExists:copy[active].error)}finally{button.disabled=false;label.textContent=original}});

if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/service-worker.js').catch(error=>console.warn('PWA registration failed',error)));
